[WIP] Add the function to generate metasploit-framework module list
vulsio/msfdb-list-updater pull request #1
Opened 2020-06-05 08:08 UTC by takuzoo3868

This set of codes will be used for the detection of **Vuls** in the future. 
The functions provided are as follows.

# What did you implement:

- Fetch the latest msf to the cache directory
- Update msfdb-list which stores CVE list for detection
- Extracting the necessary information from the module scripts

Modules in the CVE are biased towards **auxiliary & exploits**, 
so I added the updater code to these two.

**NOTICE**: Push to msfdb-list repo will be implemented after the review...

# How Has This Been Tested?

The samples are used to test the regular expression-related parts of the code.

# Others

### Usage

```
$ msfdb-list-updater -h
Usage of msfdb-list-updater:
  -target string
        update target (msf)
```

<img width="833" alt="スクリーンショット 2020-06-05 16 51 25" src="https://user-images.githubusercontent.com/18602067/83851190-f5b73880-a74c-11ea-9dba-8776a5018145.png">

### msfdb-list
By executing the code, the configuration of msfdb-list is as follows.

```
$ tree -L 2
.
├── README.md
├── last_updated.json
└── rapid7
    ├── 1999
    ├── 2000
    ├── 2001
    ├── 2002
    ├── 2003
    ├── 2004
    ├── 2005
    ├── 2006
    ├── 2007
    ├── 2008
    ├── 2009
    ├── 2010
    ├── 2011
    ├── 2012
    ├── 2013
    ├── 2014
    ├── 2015
    ├── 2016
    ├── 2017
    ├── 2018
    ├── 2019
    └── 2020
```

```
$ bat rapid7/2020/CVE-2020-0618.json
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: rapid7/2020/CVE-2020-0618.json
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ {
   2   │   "Name": "ssrs_navcorrector_viewstate.rb",
   3   │   "Title": "SQL Server Reporting Services (SSRS) ViewState Deserialization",
   4   │   "Discription": "A vulnerability exists within Microsoft's SQL Server Reporting Services which can allow an
       │ attacker to craft an HTTP POST request with a serialized object to achieve remote code execution. The vulnera
       │ bility is due to the fact that the serialized blob is not signed by the server.",
   5   │   "CveIDs": [
   6   │     "CVE-2020-0618"
   7   │   ],
   8   │   "RefURLs": [
   9   │     "https://www.mdsec.co.uk/2020/02/cve-2020-0618-rce-in-sql-server-reporting-services-ssrs/"
  10   │   ]
  11   │ }
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

2020-06-24 03:02 UTC, kotakanbe requested changes

2020-06-24 03:02 UTC, kotakanbe commented on utils/utils.go
> +func SaveCVEPerYear(dirName string, cveID string, data interface{}) error {
Why is data an interface, and why not a struct? 
I think a struct doesn't require any casting and is more maintainable.

2020-06-24 03:02 UTC, kotakanbe commented on utils/utils.go
> +	b = bytes.Replace(b, []byte("\\u003c"), []byte("<"), -1)
We should use API
https://stackoverflow.com/a/39079218

2020-06-24 03:02 UTC, kotakanbe commented on msf/msf.go
> +func formatDescription(match [][]byte) string {
Please add a test case for this function.

2020-06-24 03:03 UTC, kotakanbe commented
Please check out some of the comments I made :)

2020-06-24 05:28 UTC, takuzoo3868 commented on msf/msf.go
> +func formatDescription(match [][]byte) string {
This function is included in the Parse test.   
Should I set up a separate test case to check it?

2020-06-25 07:36 UTC, kotakanbe approved these changes
LGTM

2020-06-25 07:40 UTC, merged